###### Ddatabase Worker Config ######

# how many database worker goroutines are spun up
db_num_workers: 16

# polling frequency in milliseconds for the worker_chan. longer
# polling intervals will produce fewer DB updates overall, resulting
# in higher throughput at the expense of slightly increased latency
db_worker_poll_interval_ms: 5

# every poll_interval, the db worker will read and aggregate at most
# db_worer_batch_size before submitting the aggregated updates to the db. 
# it will stop early if the channel is empty.
# capping it at this value  will ensure we don't buffer 
# pending aggregations for too long when the server is under high load
db_worker_batch_size: 5000

# size of the channel where goroutines fielding POST requests can
# write the updates for the worker to read. 
# should meet or exceed the db_worker_batch_size
db_worker_chan_size: 5000

###### REST Config ######
rest_api_host: "localhost"
rest_api_port: 8080

###### Embedded database Config ######

db_data_location: "./internal/.embedded-postgres-go/extracted/data"
db_binary_location: "./internal/.embedded-postgres-go/extracted"
db_runtime_location: "./internal/.embedded-postgres-go/extracted"
db_port: 5432
